import type { MetadataRoute } from "next";
import { SITE_URL } from "@/shared/lib/seo";

const MAIN_SECTIONS: Array<{ path: string; frequency: string; priority: number }> = [
  { path: "/it-support", frequency: "weekly", priority: 0.9 },
  { path: "/voice", frequency: "weekly", priority: 0.9 },
  { path: "/internet", frequency: "weekly", priority: 0.9 },
  { path: "/cloud", frequency: "weekly", priority: 0.9 },
  { path: "/web", frequency: "weekly", priority: 0.9 },
  { path: "/industries", frequency: "monthly", priority: 0.8 },
  { path: "/contact", frequency: "monthly", priority: 0.8 },
];

const SUB_SECTIONS: Array<{ path: string; priority: number }> = [
  { path: "/it-support/cyber-security", priority: 0.8 },
  { path: "/it-support/managed-it", priority: 0.8 },
  { path: "/it-support/servers-and-networking", priority: 0.8 },
  { path: "/it-support/device-repair", priority: 0.8 },
  { path: "/it-support/cyber-security/cloud-and-network-security", priority: 0.7 },
  { path: "/it-support/cyber-security/endpoint-security", priority: 0.7 },
  { path: "/it-support/cyber-security/essential-eight", priority: 0.7 },
  { path: "/it-support/cyber-security/incident-response", priority: 0.7 },
  { path: "/it-support/cyber-security/security-awareness-training", priority: 0.7 },
  { path: "/it-support/cyber-security/zero-trust-framework", priority: 0.7 },
  { path: "/voice/phone-systems/small-business", priority: 0.7 },
  { path: "/voice/phone-systems/medium-business", priority: 0.7 },
  { path: "/voice/phone-systems/enterprise-business", priority: 0.7 },
  { path: "/voice/brands", priority: 0.7 },
  { path: "/voice/brands/vodia", priority: 0.7 },
  { path: "/voice/brands/grandstream", priority: 0.7 },
  { path: "/voice/brands/avaya", priority: 0.7 },
  { path: "/voice/brands/lg-ipecs", priority: 0.7 },
  { path: "/voice/hardware/headsets", priority: 0.7 },
  { path: "/voice/hardware/cordless-phones", priority: 0.7 },
  { path: "/voice/hardware/celfi-4g-repeater", priority: 0.7 },
  { path: "/voice/features/unified-comms", priority: 0.7 },
  { path: "/voice/features/conferencing-solutions", priority: 0.7 },
  { path: "/voice/features/hold-music", priority: 0.7 },
  { path: "/voice/features/microsoft-teams", priority: 0.7 },
  { path: "/voice/features/more-features", priority: 0.7 },
  { path: "/internet/nbn", priority: 0.8 },
  { path: "/internet/nbn/home-small-business", priority: 0.7 },
  { path: "/internet/nbn/business", priority: 0.7 },
  { path: "/internet/nbn/enterprise-fibre", priority: 0.7 },
  { path: "/internet/nbn/fixed-wireless", priority: 0.7 },
  { path: "/internet/nbn/sky-muster", priority: 0.7 },
  { path: "/internet/nbn/free-fibre-upgrade", priority: 0.7 },
  { path: "/internet/nbn/order", priority: 0.6 },
  { path: "/internet/starlink", priority: 0.8 },
  { path: "/internet/cel-fi", priority: 0.8 },
  { path: "/internet/4g-5g-internet", priority: 0.8 },
  { path: "/cloud/microsoft-solutions", priority: 0.8 },
  { path: "/cloud/microsoft-solutions/microsoft-365", priority: 0.7 },
  { path: "/cloud/microsoft-solutions/onedrive", priority: 0.7 },
  { path: "/cloud/microsoft-solutions/sharepoint", priority: 0.7 },
  { path: "/cloud/microsoft-solutions/teams", priority: 0.7 },
  { path: "/cloud/microsoft-solutions/exchange-online", priority: 0.7 },
  { path: "/cloud/microsoft-solutions/defender", priority: 0.7 },
  { path: "/cloud/microsoft-solutions/intune", priority: 0.7 },
  { path: "/cloud/microsoft-solutions/entra-id", priority: 0.7 },
  { path: "/cloud/microsoft-solutions/conditional-access", priority: 0.7 },
  { path: "/cloud/microsoft-solutions/copilot", priority: 0.7 },
  { path: "/cloud/microsoft-solutions/windows-365", priority: 0.7 },
  { path: "/cloud/microsoft-solutions/azure", priority: 0.7 },
  { path: "/cloud/cyber-security", priority: 0.8 },
  { path: "/cloud/cyber-security/essential-eight", priority: 0.7 },
  { path: "/cloud/cyber-security/secure-score", priority: 0.7 },
  { path: "/cloud/cyber-security/disp", priority: 0.7 },
  { path: "/cloud/cyber-security/m365-security", priority: 0.7 },
  { path: "/cloud/cyber-security/backup-recovery", priority: 0.7 },
  { path: "/cloud/services", priority: 0.8 },
  { path: "/cloud/services/modern-workplace", priority: 0.7 },
  { path: "/cloud/services/email-signature", priority: 0.7 },
  { path: "/web/development", priority: 0.8 },
  { path: "/web/hosting", priority: 0.8 },
  { path: "/web/seo", priority: 0.8 },
  { path: "/web/ecommerce", priority: 0.8 },
  { path: "/web/portfolio", priority: 0.8 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  return [
    { url: SITE_URL, lastModified, changeFrequency: "weekly", priority: 1 },
    ...MAIN_SECTIONS.map(({ path, frequency, priority }) => ({
      url: `${SITE_URL}${path}`,
      lastModified,
      changeFrequency: frequency as MetadataRoute.Sitemap[number]["changeFrequency"],
      priority,
    })),
    ...SUB_SECTIONS.map(({ path, priority }) => ({
      url: `${SITE_URL}${path}`,
      lastModified,
      changeFrequency: "monthly" as const,
      priority,
    })),
  ];
}
